
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-demoapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dotnet-demoapp

  template:
    metadata:
      labels:
        app: dotnet-demoapp

    spec:
      containers:
        - name: demo
          image: bcdemo.azurecr.io/temp/demoapp:latest  

          ports:
            - containerPort: 5000