image:
  pullPolicy: Always

service:
  targetPort: 5000

secretEnv:
  Weather__ApiKey:
    secretName: dotnet-demoapp
    secretKey: weatherKey
  AzureAd__ClientSecret:
    secretName: dotnet-demoapp
    secretKey: aadAppSecret

env: 
  ApplicationInsights__InstrumentationKey: ace55567-7613-45ce-a2b6-f967aa74362e
  AzureAd__ClientId: 3584ac39-1ab1-4fe6-a3dd-4b2fbedc9d7d
  AzureAd__Instance: https://login.microsoftonline.com/
  AzureAd__TenantId: common
  AzureAd__CallbackPath: /signin-oidc

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: 
    enabled: true
    secretName: kube-benco-io-cert